### ISSUE TITLE
Safe mode in v0.1.8 iOS 10.3.2

### ISSUE THREAD

**Issue by MhmdSAbdlh** [ryst/PortraitLock#2]
Hi
I try the last version(0.1.8) in my iPhone 6 with iOS 10.3.2 and its go to safe mode directly after install it.
So i check the version 0.1.7-1 and its work.
Thanks you for your work <3 and Sorry for my bad english :')

**Comment by dado3212** [comment]
This is no longer being maintained, and can instead be supported by https://github.com/dado3212/PortraitLock.  Did you try version 1.8.2, and did it resolve your issue?
